### ISSUE TITLE
大佬这个怎样解决？

### ISSUE THREAD

**Issue by jskjdd** [kxs2018/daily_sign#6]
Traceback (most recent call last):
  File "./scripts/unicom.py", line 664, in <module>
    main()
  File "./scripts/unicom.py", line 659, in main
    QYWX_Notify().send('联通APP签到信息', digest, content)
  File "/home/runner/work/-daily123/-daily123/scripts/QYWX_Notify.py", line 13, in __init__
    self.access_token = self.__get_access_token()
  File "/home/runner/work/-daily123/-daily123/scripts/QYWX_Notify.py", line 27, in __get_access_token
    raise Exception('Please check if corpid and corpsecret are correct \n' + resp.text)
Exception: Please check if corpid and corpsecret are correct 
{"errcode":41004,"errmsg":"corpsecret missing"}
Error: Process completed with exit code 1.

**Comment by kxs2018** [comment]
> Traceback (most recent call last): File "./scripts/unicom.py", line 664, in main() File "./scripts/unicom.py", line 659, in main QYWX_Notify().send('联通APP签到信息', digest, content) File "/home/runner/work/-daily123/-daily123/scripts/QYWX_Notify.py", line 13, in **init** self.access_token = self.__get_access_token() File "/home/runner/work/-daily123/-daily123/scripts/QYWX_Notify.py", line 27, in __get_access_token raise Exception('Please check if corpid and corpsecret are correct \n' + resp.text) Exception: Please check if corpid and corpsecret are correct {"errcode":41004,"errmsg":"corpsecret missing"} Error: Process completed with exit code 1.

企业微信的信息没存到secret里

**Comment by jskjdd** [comment]
怎样把企业微信换成其他接受通知的比如pushplus
